version: '3.8'

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm install && npm test"
    volumes:
      - .:/app
    working_dir: /app

  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm install --prod && npm start"
    volumes:
      - .:/app
    working_dir: /app
