name: Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install modules
      run: yarn

    - name: Run ESLint
      run: eslint . --ext .js,.ts,.tsx

