name: Run Test Suite

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: docker-compose build ci --no-cache

    - name: Run tests
      run: docker-compose run ci

